plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.10' apply false
    id 'org.relativitymc.neo-loom' version '1.17-SNAPSHOT' apply false
    id "dev.yumi.gradle.licenser" version "4.0.+" apply false
    id 'me.modmuss50.mod-publish-plugin' version '2.0.0-beta.1'
}

gradle.projectsEvaluated {

    publishMods {
        type = STABLE
        def changelogFile = rootProject.file("./changelogs/${project.mod_version}.md")

        if (changelogFile.exists()) {
            changelog = changelogFile.text
        }

        for (loader in [':common', ':fabric', ':neoforge']) {
            def loaderProject = project(loader)
            additionalFiles.from(loaderProject.tasks.named('jar', Jar).map { it.archiveFile })
            additionalFiles.from(loaderProject.tasks.named('sourcesJar', Jar).map { it.archiveFile })
            additionalFiles.from(loaderProject.tasks.named('javadocJar', Jar).map { it.archiveFile })
        }

        github {
            repository = "TheDeathlyCow/thermoo"
            accessToken = providers.environmentVariable("RELEASE_GITHUB_TOKEN")
            commitish = "26.1.x"
            tagName = "v${project.mod_version}"

            displayName = "[26.1.x] Thermoo ${project.mod_version}"
        }
    }
}