# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true


# Fabric Properties
minecraft_version=26.1-snapshot-10
loader_version=0.18.4

# Mod Properties
mod_version=9.1.0
maven_group=com.github.thedeathlycow
archives_base_name=thermoo

# Dependencies
fabric_version=0.143.7+26.1
cca_version=8.0.0-alpha.2
polymer_version=0.15.0-beta.4+1.21.11-rc2
