# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
loader_version_range=[1,)

## Mod Properties

mod_id=thermoo
mod_name=Thermoo
mod_license=LGPL-3.0
mod_version=4.8.1-neoforge
mod_group_id=com.github.thedeathlycow.thermoo
mod_authors=TheDeathlyCow
mod_description=A temperature library for Fabric mods

ffapi_version=0.115.6+2.1.4+1.21.1