# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true


# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

# Mod Properties
mod_version=5.3.1
maven_group=com.github.thedeathlycow
archives_base_name=thermoo

#Fabric api
fabric_version=0.118.5+1.21.4

# Cardinal components
cca_version=6.2.2
