plugins {
    id 'multiloader-common'
    id 'org.relativitymc.neo-loom'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    // use this to get mixins and asm in the common module, do not use fabric classes in common!!!!!
    compileOnly "net.fabricmc:fabric-loader:${project.fabric_loader_version}"

    api("dev.yumi.commons:yumi-commons:${project.yumi_version}")
    api("dev.yumi.commons:yumi-commons-core:${project.yumi_version}")
    api("dev.yumi.commons:yumi-commons-collections:${project.yumi_version}")
    api("dev.yumi.commons:yumi-commons-event:${project.yumi_version}")
    implementation("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_mc_foundation_version}")

    include("dev.yumi.commons:yumi-commons:${project.yumi_version}")
    include("dev.yumi.commons:yumi-commons-core:${project.yumi_version}")
    include("dev.yumi.commons:yumi-commons-collections:${project.yumi_version}")
    include("dev.yumi.commons:yumi-commons-event:${project.yumi_version}")
    include("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_mc_foundation_version}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    interfaceInjection {
        enableDependencyInterfaceInjection = true
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonKotlin {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonKotlin sourceSets.main.kotlin.sourceDirectories.filter { !it.name.endsWith("java") }.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}

//publishMods {
//    type = STABLE
//    changelog = rootProject.file("./changelogs/${project.version}.md").text
//
//    github {
//        repository = "TheDeathlyCow/novoatlas"
//        accessToken = providers.environmentVariable("RELEASE_GITHUB_TOKEN")
//        commitish = "26.1.x"
//        tagName = "${project.version}"
//
//        displayName = "[26.1.x] NovoAtlas Example Datapacks ${project.version}"
//
//        additionalFiles.from(project.extensions.datapackArchives)
//    }
//}