plugins {
    id 'multiloader-common'
    id 'org.relativitymc.neo-loom'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    // use this to get mixins and asm in the common module, do not use fabric classes in common!!!!!
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"

    api("dev.yumi.commons:yumi-commons:${project.yumi_version}")
    api("dev.yumi.commons:yumi-commons-core:${project.yumi_version}")
    api("dev.yumi.commons:yumi-commons-collections:${project.yumi_version}")
    api("dev.yumi.commons:yumi-commons-event:${project.yumi_version}")

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
    implementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"

    include("dev.yumi.commons:yumi-commons:${project.yumi_version}")
    include("dev.yumi.commons:yumi-commons-core:${project.yumi_version}")
    include("dev.yumi.commons:yumi-commons-collections:${project.yumi_version}")
    include("dev.yumi.commons:yumi-commons-event:${project.yumi_version}")

    compileOnly "eu.pb4:polymer-core:${project.polymer_version}"
    compileOnly "eu.pb4:polymer-networking:${project.polymer_version}"

    testImplementation "net.fabricmc:fabric-loader-junit:${project.fabric_loader_version}"
    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation "org.mockito:mockito-core:3.+"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    interfaceInjection {
        enableDependencyInterfaceInjection = true
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonKotlin {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonKotlin sourceSets.main.kotlin.sourceDirectories.filter { !it.name.endsWith("java") }.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}

//publishMods {
//    type = STABLE
//    changelog = rootProject.file("./changelogs/${project.version}.md").text
//
//    github {
//        repository = "TheDeathlyCow/novoatlas"
//        accessToken = providers.environmentVariable("RELEASE_GITHUB_TOKEN")
//        commitish = "26.1.x"
//        tagName = "${project.version}"
//
//        displayName = "[26.1.x] NovoAtlas Example Datapacks ${project.version}"
//
//        additionalFiles.from(project.extensions.datapackArchives)
//    }
//}