plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

def commonProject = project(':common')

dependencies {
    implementation("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_mc_foundation_version}")

    // this is literally just to make the game tests work...
    implementation("maven.modrinth:unruled-api:${project.unruled_version}")

    jarJar("dev.yumi.commons:yumi-commons:${project.yumi_version}")
    jarJar("dev.yumi.commons:yumi-commons-core:${project.yumi_version}")
    jarJar("dev.yumi.commons:yumi-commons-collections:${project.yumi_version}")
    jarJar("dev.yumi.commons:yumi-commons-event:${project.yumi_version}")
    jarJar("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_mc_foundation_version}")

    gametestImplementation commonProject.sourceSets.gametest.output
}

neoForge {
    version = project.neoforge_version

    def at = file("src/main/resources/META-INF/accesstransformer.cfg")
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        clientManualTest {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', "${project.mod_id},${project.mod_id}_test"
        }

        serverManualTest {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', "${project.mod_id},${project.mod_id}_test"
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', "${project.mod_id},${project.mod_id}_test"
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }

        "${mod_id}_test" {
            sourceSet(sourceSets.gametest)
        }
    }

    interfaceInjectionData.from file('src/main/resources/interfaces.json').absolutePath

    interfaceInjectionData {
        publish file('src/main/resources/interfaces.json')
    }
}

tasks.named('build') {
    dependsOn('runGameTest')
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}

publishMods {
    changelog = rootProject.file("./changelogs/${project.version}.md").text
    type = STABLE

    file = jar.archiveFile
    additionalFiles.from(sourcesJar.archiveFile)
    additionalFiles.from(javadocJar.archiveFile)
    displayName = "Thermoo NeoForge ${project.version}"

    modLoaders.add("neoforge")

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "846544"
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2")

        javaVersions.add(JavaVersion.VERSION_25)

        clientRequired = false
        serverRequired = true

        requires("unruled-api")

        optional("thermoo-patches")
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "9TbXlAut"
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2")

        requires("unruled-api")

        optional("thermoo-patches")
    }
}