name: Release GitHub
on: [ workflow_dispatch ] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew build publishGithub
        env:
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}